export const FETCH_NEWS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const PUBLISH_NEWS_SUCCESS = 'PUBLISH_NEWS_SUCCESS';